# Generated by Django 4.2.3 on 2023-12-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='tags',
        ),
    ]
