# Generated by Django 4.2.3 on 2023-12-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_residence_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile',
            new_name='mobile1',
        ),
        migrations.AddField(
            model_name='address',
            name='mobile2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
