# Generated by Django 4.2.3 on 2024-01-06 17:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_residence_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='facilities',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the Redidence', null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='features',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the Redidence', null=True),
        ),
    ]
