# Generated by Django 4.2.3 on 2024-01-06 17:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_residence_facilities_residence_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='policies',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the Redidence', null=True),
        ),
    ]
