# Generated by Django 4.2.3 on 2024-01-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_residence_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='specifications',
        ),
    ]
