# Generated by Django 4.2.3 on 2024-01-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_residence_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='authentic_rating',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='chat_resp_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
    ]
